# Generated by Django 4.1.7 on 2023-03-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_cry_mercy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='country',
            field=models.CharField(default='Kenya', max_length=50),
        ),
    ]
