# Generated by Django 4.1.7 on 2023-03-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_cry_mercy', '0003_student_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='amount',
            field=models.IntegerField(default='100', max_length=50),
        ),
    ]
