# Generated by Django 4.1.7 on 2023-03-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_cry_mercy', '0005_alter_student_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='amount',
            field=models.IntegerField(default='1'),
        ),
    ]
